
x-airflow-common: &airflow-common
  build:
    context: ..
    dockerfile: docker/Dockerfile
  environment:
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AWS_ACCESS_KEY_ID: KIA2QCN3VA5N62MN2W7
    AWS_SECRET_ACCESS_KEY: MaPFGrg8xYLVNUitIQUI8GkvZ3PGjSorPg9P/2g4
    AWS_DEFAULT_REGION: ap-south-1
    S3_BUCKET: pipeline-data-sh
  volumes:
    - ../dags:/opt/airflow/dags
    - ../ingestion:/opt/airflow/ingestion
    - ../ge:/opt/airflow/ge
    - ../logs:/opt/airflow/logs
  depends_on:
    postgres:
      condition: service_healthy

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5

  airflow-init:
    <<: *airflow-common
    command: db init
    restart: on-failure

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8080:8080"
    restart: always

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    restart: always